(import (rnrs)
        (rnrs arithmetic bitwise))

(define (sieve n)
  (if (< n 2)
      '()
      (let ((prime? (make-vector (+ n 1) #t)))
        (vector-set! prime? 0 #f)
        (vector-set! prime? 1 #f)
        (let mark ((p 2))
          (when (<= (* p p) n)
            (when (vector-ref prime? p)
              (let multiples ((multiple (* p p)))
                (when (<= multiple n)
                  (vector-set! prime? multiple #f)
                  (multiples (+ multiple p)))))
            (mark (+ p 1))))
        (let collect ((value 2) (primes '()))
          (if (> value n)
              (reverse primes)
              (collect (+ value 1)
                       (if (vector-ref prime? value)
                           (cons value primes)
                           primes)))))))
