(import (rnrs))

(define (roman n)
  (assert (and (integer? n) (<= 1 n 3999)))
  (let ((symbols '((1000 . "M") (900 . "CM") (500 . "D") (400 . "CD")
                   (100 . "C") (90 . "XC") (50 . "L") (40 . "XL")
                   (10 . "X") (9 . "IX") (5 . "V") (4 . "IV") (1 . "I"))))
    (let loop ((remaining n) (values symbols) (parts '()))
      (if (= remaining 0)
          (apply string-append (reverse parts))
          (let* ((entry (car values)) (value (car entry)) (glyph (cdr entry)))
            (if (>= remaining value)
                (loop (- remaining value) values (cons glyph parts))
                (loop remaining (cdr values) parts)))))))
