name: Auto Merge Exercism Bot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge for Exercism-bot PRs
        # This condition ensures only PRs from the Exercism-bot actor are auto-merged
        if: github.actor == 'Exercism-bot' 
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MERGE_METHOD: "squash"
